### ISSUE TITLE
[BUG] Cannot destructure property 'body' in the bulk helper after result has been returned to the caller

### ISSUE THREAD

**Issue by sebekz** [opensearch-project/opensearch-js#185]
**What is the bug?**
I am getting an error when trying to use the `client.helpers.bulk` helper. 

```
TypeError: Cannot destructure property 'body' of 'undefined' as it is undefined.
      at node_modules/@opensearch-project/opensearch/lib/Helpers.js:704:93
```

**How can one reproduce the bug?**

I created an isolated test to illustrate the issue. Hopefully it's easily reproducible this way. 

```
import { Client } from '@opensearch-project/opensearch';
import * as AWS from 'aws-sdk';

// My fork of https://www.npmjs.com/package/aws-elasticsearch-connector capable of signing requests to AWS OpenSearch
// @opensearch-project/opensearch is not yet capable of signing AWS requests
const createAwsElasticsearchConnector = require('../modules/aws-oss-connector');

const domain =
  'PUT_YOUR_DOMAIN_URL_HERE.es.amazonaws.com';
const index = 'YOUR_TEST_INDEX_NAME';

const bootstrapOSSClient = (): Client => {
  const ossConnectorConfig = createAwsElasticsearchConnector(AWS.config);
  const client = new Client({
    ...ossConnectorConfig,
    node: `https://${domain}`,
  });

  return client;
};

const main = async (): Promise<void> => {
  try {
    console.info('Starting processing');

    // TEST DEFINITION
    const input = [
      { id: '1', name: 'test' },
      { id: '2', name: 'test 2' },
    ];

    const client = bootstrapOSSClient();

    const response = await client.helpers.bulk({
      datasource: input,
      onDocument(doc: any) {
        console.info(`Processing document #${doc.id}`);
        return {
          index: { _index: index, _id: doc.id },
        };
      },
    });

    console.info(`Indexed ${response.successful} documents`);

    // END TEST DEFINITION

    console.info('Finished processing');
  } catch (error) {
    console.warn(`Error in main(): ${error}`);
  }
};

try {
  main().then(() => {
    console.info('Exited main()');
  });
} catch (error) {
  console.warn(`Top-level error: ${error}`);
}
```

and the result was

```
$ npx ts-node ./.vscode/test.ts
Starting processing
Processing document #1
Processing document #2
(node:39232) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'body' of 'undefined' as it is undefined.
    at D:\Development\eSUB\Coronado\git\platform\node_modules\@opensearch-project\opensearch\lib\Helpers.js:704:93
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Indexed 2 documents
Finished processing
Exited main()
```

Stepping through the code I am able to intercept a single call to `node_modules/@opensearch-project/opensearch/lib/Helpers.js:704:93` where

- `client.bulk()` is called
- which calls `bulkApi()` in `\opensearch\api\api\bulk.js` and returns successfully
- `await finish()` is called in `\opensearch\lib\Helpers.js:559`
- inside `\opensearch\lib\Transport.js` a call to `prepareRequest()` is made, ending with `return transportReturn`
- this ends up in `request():177` calling

```
return p.then(onFulfilled, onRejected)
```
with `p` being `null` at that time. That resulted my callback in the AWS Transport class responsible for signing requests to callback to the `Helper.js tryBulk()` with second parameter undefined, resulting in the `Cannot destructure property 'body'` error.

**What is the expected behavior?**
`Transport.js` implementation of the request does not result in a null `p` promise issue when callback is passed in the `request() call`

**What is your host/environment?**
 - VS Code + Node v14 + ES5
 - Connecting to OSS 1.0 instance in AWS

**Do you have any additional context?**
Looks to be identical as [this SO unresolved issue](https://stackoverflow.com/questions/65254156/elasticsearch-js-body-is-undefined)

**Comment by kavilla** [comment]
Sorry about the delay. Thank you @apostrophest for the details!

Gotcha will try to get some prioritization then!

**Comment by dblock** [comment]
@curena-contrast Want to pick it up and fix it? At least maybe write a failing test for it?
