### ISSUE TITLE
opesearch NPM connection issue on high load with AWS opensearch

### ISSUE THREAD

**Issue by shashank-sachan** [opensearch-project/opensearch-js#198]
**Describe the bug**
We are trying to replace the elasticsearch NPM with opensearch NPM in our project (using AWS opensearch 1.0 cluster).
We are connecting to AWS opensearch from AWS lambda.
Now in case of high load we start getting _ConnectionError: getaddrinfo EMFILE_ error.  

```
ConnectionError: getaddrinfo EMFILE *******.us-****-1.es.amazonaws.com
    at ClientRequest.onError (/opt/nodejs/node_modules/@opensearch-project/opensearch/lib/Connection.js:126:16)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  meta: {
    body: null,
    statusCode: null,
    headers: null,
    meta: {
      context: null,
      request: {...},
      name: 'opensearch-js',
      connection: {
        url: 'https://*******.us-****-1.es.amazonaws.com/',
        id: 'https://*******.us-****-1.es.amazonaws.com/',
        headers: {},
        deadCount: 4,
        resurrectTimeout: 1636607063285,
        _openRequests: 0,
        status: 'dead',
        roles: { master: true, data: true, ingest: true }
      },
      attempts: 3,
      aborted: false
    }
  }
}
```

If I put elasticsearch NPM back then it works fine.
By looking at the error, it looks like that there is host resolution problem and doesn't seem related to opensearch. But same host works fine with elasticsearch NPM.
Also this is working fine with opensearch NPM when there is low traffic. But when there is high load it starts giving error.
Is there any internal issue with opensearch http connection management?

**Plugins**
elasticsearch: "^16.5.0"
@opensearch-project/opensearch: "^1.0.0"

**Host/Environment (please complete the following information):**
AWS lambda

**Comment by jnith** [comment]
Hi! Is there an update on how this issue was resolved? I'm facing the same error with OpensSearch host

**Comment by dblock** [comment]
@jnith @shashank-sachan it sounds like opensearch-js is causing the system to run out of file descriptors

What's your output from `ulimit -a`? Generally this is 1024. There's a bunch of articles on how to increase it ([example](https://www.tecmint.com/increase-set-open-file-limits-in-linux/)), I would try that as a workaround.

If you can reproduce this consistently, let's see the output of `lsof` and `lsof -n -i -P` (from [this SO](https://stackoverflow.com/questions/10355501/connect-emfile-error-in-node-js)).  

It's possible that this client/server combination has higher throughput than the elasticsearch one and causes you to hit a limit earlier under load.

**Comment by jnith** [comment]
Yes thanks for the details. I was able to figure out that the issue was causing because each update request to openSearch is creating a new connection and I was creating 1000s of connection. I was able to overcome the issue with the Bulk update feature and hence limiting the number of connections.

**Comment by shashank-sachan** [comment]
@dblock I'm using this inside AWS lambda so I don't have control over ulimit.
But elasticsearch-js was not causing this issue so may be we need to the optimization in this library.

**Comment by dblock** [comment]
@shashank-sachan Which version of elasticsearch-js were you using? Need to track down the diff (help wanted). Either way sounds like we're creating some unbounded number of connections, which should be replaced by a pool.

**Comment by hongkheng** [comment]
Recently been hitting the same issue, is there a way to control the number of connections? It seems like it's already using ConnectionPool by default. Notice the `ConnectionPool` is reporting connection is `alive` when the request is already `dead`.

**Comment by perttu-n** [comment]
I had exactly the same problem when replacing ElasticSearch client with OpenSearch client. The problem fix was simple: just call client's `close` function when you're finished with the client. In my case, the client is re-created per lambda instance invoke (the same client is not reused in different invocations).

Sadly the use of close is not documented in OpenSearch Javascript client docs. Only Java documentation says that you should close the client when you're finished.

**Comment by dblock** [comment]
@perttu-n Care to add it to the documentation?

**Comment by arnabrahman** [comment]
I am having the same issue while replacing the elasticsearch client. I am running it from lambda. Previously I was using the `elasticsearch` 16.3 version.

**Comment by arnabrahman** [comment]
Ok so after spending a day on this, i solved it. I realized the client initialization was happening inside the handler function of lambda. So, I just moved the initialization part out of the handler function. So, now it's using the same client instance as long as the lambda is alive.

**Comment by dblock** [comment]
@arnabrahman Would you care to contribute something to the documentation/samples? Maybe an example for Lambda with some cautionary tales?

**Comment by arnabrahman** [comment]
@dblock Sure, happy to contribute to open source. Let me know how to get started.

**Comment by dblock** [comment]
@arnabrahman You can get started here: https://github.com/opensearch-project/.github/blob/main/ONBOARDING.md. Thanks!

**Comment by arnabrahman** [comment]
@dblock created a PR of the explanation in the doc.

**Comment by dblock** [comment]
@arnabrahman do you think we should close this one?

**Comment by arnabrahman** [comment]
@dblock Maybe, we have added an explanation in the documentation to guide users in avoiding this problem. 

However, it's worth noting that the previous Elasticsearch client did not encounter such issues. So, if it's possible then we should look into code to see why it's behaving differently.
