### ISSUE TITLE
[BUG] "Cannot read property 'then' of null" in Transport.js

### ISSUE THREAD

**Issue by alexrayan** [opensearch-project/opensearch-js#253]
**What is the bug?**
response TypeError: Cannot read property 'then' of null
    at Object.then (@opensearch-project/opensearch/lib/Transport.js:185:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

The same issue has been reported and fixed in the elasticsearch official client here: 
https://github.com/elastic/elasticsearch-js/issues/1521

**Comment by alexrayan** [comment]
I'm be happy to submit a PR with the same fix that has been implemented in the elastic/elasticsearch-js client.

**Comment by ananzh** [comment]
Hi @alexrayan thanks for reporting and fixing the issue. Our client is forked from 7.14 but we do remove some changes between 7.10-7.14. I am trying to reproduce this issue using [this example ](https://github.com/elastic/elasticsearch-js/issues/1521#issuecomment-900045628):

```
'use strict';
const delay = () => new Promise(res => setTimeout(res, 10));
var { Client } = require('@opensearch-project/opensearch');
var { Transport } = require('@opensearch-project/opensearch');
var fs = require('fs');
const cached = new Client({
    nodes: ['http://localhost:9200/'],

    // This mimicks aws-elasticsearch-connector
    Transport: class extends Transport {
        request(params, options = {}, callback) {
            if (typeof options === 'function') {
                callback = options
                options = {}
            }

            if (typeof callback === 'undefined') {
                return delay()
                    .then(() => super.request(params, options));
            }

            // Callback support
            delay()
                .then(() => super.request(params, options, callback));
        }
    }
});

(async () => {
    await cached.search({});
    console.log('End');
})();
```

Here is the response

```
~/work/client$ node data-null.js 
End

```

I don't see any issues. Meanwhile, I only loaded your unit test and expect to see some issues without ur fixing:

```
yarn tap test/unit/client.test.js
yarn run v1.22.19
$ /home/ubuntu/work/opensearch-js/node_modules/.bin/tap test/unit/client.test.js
test/unit/client.test.js 2> (node:1640204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of null
test/unit/client.test.js 2>     at Object.then (/home/ubuntu/work/opensearch-js/lib/Transport.js:185:18)
test/unit/client.test.js 2> (Use `node --trace-warnings ...` to show where the warning was created)
test/unit/client.test.js 2> (node:1640204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
test/unit/client.test.js 2> (node:1640204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  test/unit/client.test.js 120 OK 14s

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   1 passed, 1 of 1 completed
Asserts:  120 passed, of 120
Time:     14s
Done in 14.90s.
```

It seems without the change, the updated unit test is still able to pass. 

I haven't searched too deep on the cause of linked issue, just try to understand and reproduce. If you could help me to reproduce it, that would be very helpful.
