### ISSUE TITLE
[BUG] TypeError: this.emit is not a function at prepareRequest

### ISSUE THREAD

**Issue by leetn00b** [opensearch-project/opensearch-js#570]
### What is the bug?

Does anyone have any ideas as to why this error is showing up?

```
TypeError: this.emit is not a function\n at prepareRequest (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Transport.js:439:12)\n at request (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Transport.js:438:28)\n at request (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/aws/AwsSigv4Signer.js
```

**Comment by nhtruong** [comment]
Do you have more information? Especially the OS Client version and what code you ran that lead to that error.

**Comment by nhtruong** [comment]
Closing due to lack of information.
